leftnav:
- identifier: acdc59a3-3b74-ea3a-c5bb-3bc54846ee7d
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 3e97bce0-3071-7c97-6ac2-e50e9b4eccf8
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 8d2c49a0-db1a-6d48-21bb-574ef32f091b
  name: Instructor Insights
  url: /pages/instructor-insights
  weight: 30
- identifier: 7ba99210-a90b-6988-8271-2773167a1308
  name: References
  url: /pages/references
  weight: 40
- identifier: 64448bff-263d-c13c-7710-87c317c5f175
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 50
- identifier: 4e299e1e-dfbb-7247-7844-7be60e8f96c9
  name: Assignments
  url: /pages/assignments
  weight: 60
